export const AI_MODEL_REGISTRY_SCHEMA_VERSION = '1.0' as const;

export const AI_MODEL_ROLES = ['text-generation','vision-language','embedding','reranker','asr','ocr','other'] as const;
export type AiModelRole = (typeof AI_MODEL_ROLES)[number];
export const AI_MODEL_DELIVERY_KINDS = ['local-artifact','provider-api'] as const;
export type AiModelDeliveryKind = (typeof AI_MODEL_DELIVERY_KINDS)[number];

export interface AiRegistryEvidenceRefV1 { evidenceId: string; version: string; }
export interface AiPromptRegistryEntryV1 { schemaVersion: typeof AI_MODEL_REGISTRY_SCHEMA_VERSION; promptId: string; promptVersion: string; purpose: string; templateArtifactId: string; templateSha256: string; inputSchemaVersion: string; outputSchemaVersion: string; status: 'draft'|'approved'|'archived'; createdAt: string; }
export interface AiLocalModelArtifactV1 { deliveryKind: 'local-artifact'; artifactId: string; artifactSha256: string; artifactFormat: string; sourceProvenance: AiRegistryEvidenceRefV1; rightsTerms: AiRegistryEvidenceRefV1; }
export interface AiProviderModelArtifactV1 { deliveryKind: 'provider-api'; providerId: string; providerModelRef: string; termsEvidence: AiRegistryEvidenceRefV1; credentialRef?: string; }
export type AiModelArtifactLocatorV1 = AiLocalModelArtifactV1 | AiProviderModelArtifactV1;
export interface AiModelRegistryEntryV1 { schemaVersion: typeof AI_MODEL_REGISTRY_SCHEMA_VERSION; modelId: string; modelVersion: string; role: AiModelRole; artifact: AiModelArtifactLocatorV1; compatibility: { inputSchemaVersion: string; outputSchemaVersion: string; }; status: 'candidate'|'approved'|'retired'; createdAt: string; }
export interface AiExecutionProfileV1 { schemaVersion: typeof AI_MODEL_REGISTRY_SCHEMA_VERSION; profileId: string; profileVersion: string; model: {modelId:string;modelVersion:string}; prompt?: {promptId:string;promptVersion:string}; decodingPolicyVersion: string; scoringPolicyVersion?: string; createdAt: string; }
export interface AiRegistryValidationResult { valid:boolean; errors:string[]; }

const SHA256=/^[a-f0-9]{64}$/i;
const MUTABLE_ALIASES=new Set(['latest','main','master','stable','default','current']);
const SECRETISH=/^(?:sk-|AIza|ghp_|github_pat_|xox[baprs]-)/;
const nonEmpty=(value:string):boolean=>value.trim().length>0;
const validTimestamp=(value:string):boolean=>Number.isFinite(Date.parse(value));
const pinnedVersion=(value:string):boolean=>{const normalized=value.trim().toLowerCase();return normalized.length>0&&!MUTABLE_ALIASES.has(normalized)};
const evidenceValid=(value:AiRegistryEvidenceRefV1):boolean=>nonEmpty(value.evidenceId)&&pinnedVersion(value.version);

export function validateAiPromptRegistryEntryV1(entry:AiPromptRegistryEntryV1):AiRegistryValidationResult { const errors:string[]=[]; if(entry.schemaVersion!==AI_MODEL_REGISTRY_SCHEMA_VERSION)errors.push('schemaVersion must be 1.0'); if(!nonEmpty(entry.promptId)||!pinnedVersion(entry.promptVersion))errors.push('promptId and pinned promptVersion are required'); if(!nonEmpty(entry.purpose)||!nonEmpty(entry.templateArtifactId))errors.push('purpose and templateArtifactId are required'); if(!SHA256.test(entry.templateSha256))errors.push('templateSha256 must be a SHA-256 hex digest'); if(!pinnedVersion(entry.inputSchemaVersion)||!pinnedVersion(entry.outputSchemaVersion))errors.push('input/output schema versions must be pinned'); if(!validTimestamp(entry.createdAt))errors.push('createdAt must be a valid timestamp'); return {valid:errors.length===0,errors}; }
export function validateAiModelRegistryEntryV1(entry:AiModelRegistryEntryV1):AiRegistryValidationResult { const errors:string[]=[]; if(entry.schemaVersion!==AI_MODEL_REGISTRY_SCHEMA_VERSION)errors.push('schemaVersion must be 1.0'); if(!nonEmpty(entry.modelId)||!pinnedVersion(entry.modelVersion))errors.push('modelId and pinned modelVersion are required'); if(!AI_MODEL_ROLES.includes(entry.role))errors.push('role is unsupported'); if(!pinnedVersion(entry.compatibility.inputSchemaVersion)||!pinnedVersion(entry.compatibility.outputSchemaVersion))errors.push('compatibility schema versions must be pinned'); if(!validTimestamp(entry.createdAt))errors.push('createdAt must be a valid timestamp'); if(entry.artifact.deliveryKind==='local-artifact'){ if(!nonEmpty(entry.artifact.artifactId)||!SHA256.test(entry.artifact.artifactSha256))errors.push('local model artifact requires artifactId and artifactSha256'); if(!nonEmpty(entry.artifact.artifactFormat))errors.push('local model artifactFormat is required'); if(!evidenceValid(entry.artifact.sourceProvenance)||!evidenceValid(entry.artifact.rightsTerms))errors.push('local model requires versioned provenance and rights/terms evidence'); } else { if(!nonEmpty(entry.artifact.providerId)||!pinnedVersion(entry.artifact.providerModelRef))errors.push('provider model requires providerId and pinned providerModelRef'); if(!evidenceValid(entry.artifact.termsEvidence))errors.push('provider model requires versioned terms evidence'); if(entry.artifact.credentialRef!==undefined){ if(!nonEmpty(entry.artifact.credentialRef))errors.push('credentialRef must be non-empty when present'); if(SECRETISH.test(entry.artifact.credentialRef))errors.push('credentialRef must be a reference, never a raw secret'); } } return {valid:errors.length===0,errors}; }
export function validateAiExecutionProfileV1(profile:AiExecutionProfileV1):AiRegistryValidationResult { const errors:string[]=[]; if(profile.schemaVersion!==AI_MODEL_REGISTRY_SCHEMA_VERSION)errors.push('schemaVersion must be 1.0'); if(!nonEmpty(profile.profileId)||!pinnedVersion(profile.profileVersion))errors.push('profileId and pinned profileVersion are required'); if(!nonEmpty(profile.model.modelId)||!pinnedVersion(profile.model.modelVersion))errors.push('execution profile model identity must be pinned'); if(profile.prompt&&(!nonEmpty(profile.prompt.promptId)||!pinnedVersion(profile.prompt.promptVersion)))errors.push('execution profile prompt identity must be pinned'); if(!pinnedVersion(profile.decodingPolicyVersion))errors.push('decodingPolicyVersion must be pinned'); if(profile.scoringPolicyVersion!==undefined&&!pinnedVersion(profile.scoringPolicyVersion))errors.push('scoringPolicyVersion must be pinned when present'); if(!validTimestamp(profile.createdAt))errors.push('createdAt must be a valid timestamp'); return {valid:errors.length===0,errors}; }
