export const AI_STAGE_TELEMETRY_SCHEMA_VERSION = '1.0' as const;
export const AI_STAGE_TELEMETRY_AUTHORITY = 'telemetry-only' as const;
export const AI_EDITOR_STAGES = ['ingest','analyze','scene-detect','asr','embed','retrieve','rerank','plan','preview-render','final-render','export','other'] as const;
export type AiEditorStage = (typeof AI_EDITOR_STAGES)[number];
export type AiTelemetryOutcome = 'succeeded'|'failed'|'cancelled'|'skipped';
export interface AiTelemetryCorrelationV1 { projectId?:string; jobId?:string; timelineRevisionId?:string; mediaAssetId?:string; modelRunId?:string; requestId?:string; }
export interface AiTelemetryVersionRefsV1 { timelineSchemaVersion?:string; modelVersion?:string; promptVersion?:string; scoringPolicyVersion?:string; deliveryProfileVersion?:string; styleProfileVersion?:string; }
export interface AiTelemetryUsageV1 { wallDurationMs:number; cpuDurationMs?:number; gpuDurationMs?:number; inputBytes?:number; outputBytes?:number; mediaDurationMs?:number; inputTokens?:number; outputTokens?:number; cacheReadTokens?:number; }
export interface AiTelemetryCostV1 { currency:string; amountMicros:number; pricingVersion:string; }
export interface AiStageTelemetryV1 { schemaVersion:typeof AI_STAGE_TELEMETRY_SCHEMA_VERSION; authority:typeof AI_STAGE_TELEMETRY_AUTHORITY; stageRunId:string; stage:AiEditorStage; outcome:AiTelemetryOutcome; startedAt:string; completedAt:string; correlation:AiTelemetryCorrelationV1; versions?:AiTelemetryVersionRefsV1; usage:AiTelemetryUsageV1; cost?:AiTelemetryCostV1; errorCode?:string; }
export interface AiStageTelemetryValidationResult { valid:boolean; errors:string[]; }
const MUTABLE_ALIASES=new Set(['latest','main','master','stable','default','current']);
const nonEmpty=(v:string|undefined):boolean=>v===undefined||v.trim().length>0;
const nonNegativeSafe=(v:number|undefined):boolean=>v===undefined||(Number.isSafeInteger(v)&&v>=0);
const pinned=(v:string|undefined):boolean=>v===undefined||(v.trim().length>0&&!MUTABLE_ALIASES.has(v.trim().toLowerCase()));
export function validateAiStageTelemetryV1(event:AiStageTelemetryV1):AiStageTelemetryValidationResult { const errors:string[]=[]; if(event.schemaVersion!==AI_STAGE_TELEMETRY_SCHEMA_VERSION)errors.push('schemaVersion must be 1.0'); if(event.authority!==AI_STAGE_TELEMETRY_AUTHORITY)errors.push('telemetry cannot become correctness authority'); if(!event.stageRunId.trim())errors.push('stageRunId is required'); if(!AI_EDITOR_STAGES.includes(event.stage))errors.push('stage is unsupported'); const start=Date.parse(event.startedAt),end=Date.parse(event.completedAt); if(!Number.isFinite(start)||!Number.isFinite(end))errors.push('startedAt/completedAt must be valid timestamps'); else if(end<start)errors.push('completedAt must be >= startedAt'); if(!Object.values(event.correlation).every(nonEmpty))errors.push('correlation identifiers must be non-empty when present'); if(event.versions&&!Object.values(event.versions).every(pinned))errors.push('version references must be pinned when present'); for(const [key,value] of Object.entries(event.usage))if(!nonNegativeSafe(value))errors.push(`${key} must be a non-negative safe integer`); if(event.cost){if(!/^[A-Z]{3}$/.test(event.cost.currency))errors.push('cost currency must be an uppercase ISO-style code');if(!nonNegativeSafe(event.cost.amountMicros))errors.push('cost amountMicros must be a non-negative safe integer');if(!pinned(event.cost.pricingVersion))errors.push('cost pricingVersion must be pinned');} if(!nonEmpty(event.errorCode))errors.push('errorCode must be non-empty when present'); if(event.outcome==='failed'&&!event.errorCode)errors.push('failed telemetry must include stable errorCode'); return {valid:errors.length===0,errors}; }
