import {describe,expect,it} from 'vitest'; import {transitionDurableJobV1,validateDurableJobV1,type DurableJobV1} from './job-state-machine.contract.js';
const base=():DurableJobV1=>({stateMachineVersion:'1.0',jobId:'job-1',jobType:'analyze-media',idempotencyKey:'asset-1:analysis-v1',state:'queued',attempt:0,maxAttempts:2,lease:null,nextAttemptAt:null,lastErrorCode:null,createdAt:'2026-08-24T00:00:00Z',updatedAt:'2026-08-24T00:00:00Z'});
const lease=(job:DurableJobV1)=>transitionDurableJobV1(job,{type:'lease',ownerId:'worker-1',token:'token-1',now:'2026-08-24T00:01:00Z',leaseExpiresAt:'2026-08-24T00:06:00Z'}).job;
describe('durable job state machine',()=>{
 it('leases and increments attempt atomically',()=>{const j=lease(base());expect(j.state).toBe('leased');expect(j.attempt).toBe(1)});
 it('requires matching token',()=>{const j=lease(base());expect(transitionDurableJobV1(j,{type:'start',token:'wrong',now:'2026-08-24T00:02:00Z'}).ok).toBe(false)});
 it('rejects expired lease',()=>{const j=lease(base());expect(transitionDurableJobV1(j,{type:'start',token:'token-1',now:'2026-08-24T00:06:00Z'}).ok).toBe(false)});
 it('supports running -> retry-wait -> queued',()=>{let j=lease(base());j=transitionDurableJobV1(j,{type:'start',token:'token-1',now:'2026-08-24T00:02:00Z'}).job;j=transitionDurableJobV1(j,{type:'fail-retryable',token:'token-1',now:'2026-08-24T00:03:00Z',errorCode:'TEMP',nextAttemptAt:'2026-08-24T00:10:00Z'}).job;expect(j.state).toBe('retry-wait');expect(transitionDurableJobV1(j,{type:'requeue',now:'2026-08-24T00:10:00Z'}).job.state).toBe('queued')});
 it('fails terminally when attempts exhausted',()=>{const q=base();q.attempt=1;let j=lease(q);j=transitionDurableJobV1(j,{type:'start',token:'token-1',now:'2026-08-24T00:02:00Z'}).job;j=transitionDurableJobV1(j,{type:'fail-retryable',token:'token-1',now:'2026-08-24T00:03:00Z',errorCode:'TEMP',nextAttemptAt:'2026-08-24T00:10:00Z'}).job;expect(j.state).toBe('failed')});
 it('terminal success cannot be cancelled',()=>{let j=lease(base());j=transitionDurableJobV1(j,{type:'start',token:'token-1',now:'2026-08-24T00:02:00Z'}).job;j=transitionDurableJobV1(j,{type:'succeed',token:'token-1',now:'2026-08-24T00:03:00Z'}).job;expect(transitionDurableJobV1(j,{type:'cancel',now:'2026-08-24T00:04:00Z'}).ok).toBe(false)});
 it('rejects impossible persisted lease state',()=>{const j=base();j.state='running';expect(validateDurableJobV1(j).join('|')).toMatch(/require a lease/)});
 it('recovers an expired leased job back to queued without incrementing attempts',()=>{const j=lease(base());const recovered=transitionDurableJobV1(j,{type:'recover-expired',now:'2026-08-24T00:06:00Z'});expect(recovered.ok).toBe(true);expect(recovered.job.state).toBe('queued');expect(recovered.job.attempt).toBe(1);expect(recovered.job.lease).toBeNull();expect(recovered.job.lastErrorCode).toBe('LEASE_EXPIRED')});
 it('recovers an expired running job and fences the stale worker token',()=>{let j=lease(base());j=transitionDurableJobV1(j,{type:'start',token:'token-1',now:'2026-08-24T00:02:00Z'}).job;const recovered=transitionDurableJobV1(j,{type:'recover-expired',now:'2026-08-24T00:06:00Z'});expect(recovered.ok).toBe(true);const stale=transitionDurableJobV1(recovered.job,{type:'succeed',token:'token-1',now:'2026-08-24T00:06:01Z'});expect(stale.ok).toBe(false);expect(stale.error).toMatch(/active lease/)});
 it('rejects recovery while the lease is still active',()=>{const j=lease(base());const recovered=transitionDurableJobV1(j,{type:'recover-expired',now:'2026-08-24T00:05:59Z'});expect(recovered.ok).toBe(false);expect(recovered.error).toMatch(/active lease cannot be recovered/);expect(recovered.job).toEqual(j)});
 it('fails closed when an expired lease consumed the final attempt',()=>{const q=base();q.attempt=1;const j=lease(q);const recovered=transitionDurableJobV1(j,{type:'recover-expired',now:'2026-08-24T00:06:00Z'});expect(recovered.ok).toBe(true);expect(recovered.job.state).toBe('failed');expect(recovered.job.lease).toBeNull();expect(recovered.job.lastErrorCode).toBe('LEASE_EXPIRED_MAX_ATTEMPTS')});
 it('rejects expired-lease recovery for terminal and non-leased states',()=>{const queued=transitionDurableJobV1(base(),{type:'recover-expired',now:'2026-08-24T00:01:00Z'});expect(queued.ok).toBe(false);let succeeded=lease(base());succeeded=transitionDurableJobV1(succeeded,{type:'start',token:'token-1',now:'2026-08-24T00:02:00Z'}).job;succeeded=transitionDurableJobV1(succeeded,{type:'succeed',token:'token-1',now:'2026-08-24T00:03:00Z'}).job;expect(transitionDurableJobV1(succeeded,{type:'recover-expired',now:'2026-08-24T00:07:00Z'}).ok).toBe(false)});
});
